//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_UX_DashboardWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int GastoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Categoria { get; set; }
        public string Detalles { get; set; }
        public decimal Monto { get; set; }
    }
}
