//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_UX_DashboardWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionStringGuar6 : DbContext
    {
        public ConnectionStringGuar6()
            : base("name=ConnectionStringGuar6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompras { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Gasto> Gastos { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Receta_Producto> Receta_Producto { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
